import React, { useState } from "react";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import TextField from "@mui/material/TextField";
const LoginPage: React.FC = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const loginUser = async () => {
    try {
      console.log("Called");
      const response = await fetch("http://localhost:8080/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
        credentials: "include",
      });
      if (response.ok) {
        const data = await response.json();
        const { user_id, first_name, last_name, email } = data;
        console.log(data);
        localStorage.setItem(
          "user",
          JSON.stringify({ user_id, first_name, last_name, email })
        );
        router.push("/landingPage");
      } else {
        const errorData = await response.json();
        console.log(errorData);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    await loginUser();
  };

  const handleRegister = () => {
    router.push("/UserManagement/register");
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div
            // style={{ backgroundColor: "#27264E" }}
            className="p-20 shadow-2xl rounded-2xl bg-gray-50"
          >
            <h1 className="flex items-center justify-center text-black font-bold text-2xl pb-5">
              ลงชื่อเข้าใช้
            </h1>
            <div className="flex items-center justify-center pb-20 grid">
              <form onSubmit={handleSubmit} className="w-max">
                <div className="mb-6 md:flex md:items-center">
                  <div className="">
                    <TextField
                      id="outlined-basic"
                      label="Email"
                      variant="outlined"
                      className="bg-gray-50 w-max"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                </div>
                <div className="mb-6 flex items-center">
                  <div className="">
                    <TextField
                      id="outlined-basic"
                      label="Password"
                      variant="outlined"
                      className="bg-gray-50 w-max"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>
                </div>
                <div className="flex items-center">
                  <div className="">
                    <button
                      className="px-4 py-2 font-bold text-white bg-blue-300 rounded shadow hover:bg-blue-500 focus:shadow-outline focus:outline-none"
                      type="submit"
                    >
                      เข้าสู่ระบบ
                    </button>
                  </div>
                </div>
              </form>
              <div className="py-2" >
                <button onClick={handleRegister} ><p className="text-black">ยังไม่ได้เป็นสมาชิก?</p></button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default LoginPage;
